#!/bin/bash

#  launcher v1.0

#Global Variables
TARGET_IP=$1
START_DATE=$2
START_TIME=$3
CURRENT_EPOCH=$(date +%s)
TARGET_EPOCH=$(date -d "$START_DATE $START_TIME" +%s)
NAP_LENGTH=$(( $TARGET_EPOCH - $CURRENT_EPOCH ))

title() {
	echo "###################################################################"
	echo "#                                                            #"
	echo "#  launcher - singleping Schedule Utility - v1.0 - Bill Atkinson  #"
	echo "#                                                                 #"
	echo "###################################################################"
	echo
}

display_parms() {
	echo TARGET_IP: $TARGET_IP
	echo START_DATE: $START_DATE
	echo START_TIME: $START_TIME
	echo CURRENT_EPOCH: $CURRENT_EPOCH
	echo TARGET_EPOCH: $TARGET_EPOCH
	echo NAP_LENGTH: $NAP_LENGTH
	echo
}

sleep_launch() {
echo "Sleeping until start date/time.  zzzzzzzzzzzzzzzzzz...."
sleep $NAP_LENGTH

singleping $TARGET_IP
}

#Main
clear
title
if [ "$1" = "" ]; then
        echo "You did not specify an IP address.  Usage: launcher [IP] [DATE] [TIME] where IP is the IP to ping in X.X.X.X format, DATE is the target date in XX/XX/XXXX format and TIME is the time to execute in XX:XX format. Example: launcher 192.168.1.1 01/01/2020 06:00"
        echo
        exit 1
if [ "$2" = "" ]; then
        echo "You did not specify a start date.  Usage: launcher [IP] [DATE] [TIME] where IP is the IP to ping in X.X.X.X format, DATE is the target date in XX/XX/XXXX format and TIME is the time to execute in XX:XX
 format. Example: launcher 192.168.1.1 01/01/2020 06:00"
        echo
        exit 1
if [ "$3" = "" ]; then
        echo "You did not specify a start time.  Usage: launcher [IP] [DATE] [TIME] where IP is the IP to ping in X.X.X.X format, DATE is the target date in XX/XX/XXXX format and TIME is the time to execute in XX:XX
 format. Example: launcher 192.168.1.1 01/01/2020 06:00"
        echo
        exit 1
display_parms
sleep_launch
